// Generated by CoffeeScript 1.3.3
(function() {
  var Santoor, SantoorSong,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Santoor = (function() {

    function Santoor() {
      this.name = 1;
    }

    return Santoor;

  })();

  SantoorSong = (function(_super) {

    __extends(SantoorSong, _super);

    function SantoorSong() {
      return SantoorSong.__super__.constructor.apply(this, arguments);
    }

    SantoorSong.prototype.render = function() {
      return $("#main").html("Ritesh");
    };

    return SantoorSong;

  })(Backbone.View);

}).call(this);
